// Loading status actions
export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";
// auth actions
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTRATE_SUCCESS = "REGISTRATE_SUCCESS";
// Currency actions
export const CURRENCY_ALL_LOAD_SUCCESS = "CURRENCY_ALL_LOAD_SUCCESS";
export const CURRENCY_LOAD_SUCCESS = "CURRENCY_LOAD_SUCCESS";
export const CURRENCY_UPDATE_SUCCESS = "CURRENCY_UPDATE_SUCCESS";
export const CURRENCY_ADD_SUCCESS = "CURRENCY_ADD_SUCCESS";
export const CURRENCY_RATE_ADD_SUCCESS = "CURRENCY_RATE_ADD_SUCCESS";
export const CURRENCY_RATE_LOAD_SUCCESS = "CURRENCY_RATE_LOAD_SUCCESS";
export const CURRENCY_RATE_IMPORT_SUCCESS = "CURRENCY_RATE_IMPORT_SUCCESS";
// Accounts chart actions
export const ACCOUNTS_LOAD_SUCCESS = 'ACCOUNTS_LOAD_SUCCESS';
export const ACCOUNTS_ADD_SUCCESS = 'ACCOUNTS_ADD_SICCESS';
export const ACCOUNTS_UPDATE_SUCCESS = 'ACCOUNTS_UPDATE_SUCCESS';
// Bank Catalog actions
export const BANK_LOAD_SUCCESS = 'BANK_LOAD_SUCCESS';
export const BANK_ADDED_SUCCESS = 'BANK_ADDED_SUCCESS';
export const BANK_UPDATE_SUCCESS = 'BANK_ADDED_SUCCESS';
export const BANK_DELETE_SUCCESS = 'BANK_DELETE_SUCCESS';

//Clients catalog Actions

export const CLIENT_LOAD_SUCCESS = "CLIENT_LOAD_SUCCESS";
export const CLIENT_ADDED_SUCCESS = "CLIENT_ADDED_SUCCESS";
